### ISSUE TITLE
Maps Api request for each and every letter instead of a complete word

### ISSUE THREAD

**Issue by neelamnaveen86** [venkatselva8/RxPlaceAutoComplete#1]
i have worked on similar functionality in one of my projects using rxjava + retrofit the problem with your approach is that maps api is called for each and every letter typed which consumes lot of bandwidth and time instead the maps api should be called only after certain amount of letters are typed or after certain period of time which when done decrease bandwidth consumption and give appropriate results for example call maps api after 1/2 second or after typing "hyder" (hyderabad) instead of every letter that is "h", "y","d","e","r" this can easily achieved using debounce method of rxjava

**Comment by venkatselva8** [comment]
Ya. Good idea. I will update on future. I will call the API when typing every 2 letters instead of 1 letter.
